import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/layout/layout";
import HomeModule from "../components/modules/homeModule";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Photosnap</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomeModule />
    </>
  );
};

export default Home;
